title: Alexander J. Laut
email: alaut@cern.ch
description: Nuclear Engineer / Accelerator Physicist

github_username:  alaut
instagram_username: lautalexander
linkedin_username: alaut

theme: minima

# markdown: GFM

collections:
  notes:
    output: true
