title: Alexander J. Laut
email: alexander.laut@cern.ch
description: Nuclear Engineer / Accelerator Physicist

github_username:  alaut
instagram_username: lautalexander

theme: minima
plugins:
  - jekyll-feed

kramdown:
  input: GFM

collections:
  notes:
    output: true